# TCL File Generated by Component Editor 13.0sp1
# Sat Oct 26 23:45:46 JST 2013
# DO NOT MODIFY


# 
# mandelbrot_float "Floating-point Mandelbrot Calculator" v1.0
# kimu_shu 2013.10.26.23:45:46
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module mandelbrot_float
# 
set_module_property DESCRIPTION ""
set_module_property NAME mandelbrot_float
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DSP
set_module_property AUTHOR kimu_shu
set_module_property DISPLAY_NAME "Floating-point Mandelbrot Calculator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mandelbrot_float
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fpadd.qip OTHER PATH fpadd.qip
add_fileset_file fpadd.vhd VHDL PATH fpadd.vhd
add_fileset_file fpmul.qip OTHER PATH fpmul.qip
add_fileset_file fpmul.vhd VHDL PATH fpmul.vhd
add_fileset_file fpsub.qip OTHER PATH fpsub.qip
add_fileset_file fpsub.vhd VHDL PATH fpsub.vhd
add_fileset_file mandelbrot_float.vhd VHDL PATH mandelbrot_float.vhd TOP_LEVEL_FILE
add_fileset_file mb_fifo.qip OTHER PATH mb_fifo.qip
add_fileset_file mb_fifo.vhd VHDL PATH mb_fifo.vhd


# 
# parameters
# 
add_parameter LCD_BASE STD_LOGIC_VECTOR 0
set_parameter_property LCD_BASE DEFAULT_VALUE 0
set_parameter_property LCD_BASE DISPLAY_NAME LCD_BASE
set_parameter_property LCD_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property LCD_BASE UNITS None
set_parameter_property LCD_BASE ALLOWED_RANGES 0:4294967295
set_parameter_property LCD_BASE HDL_PARAMETER true
add_parameter ITER_WIDTH INTEGER 8
set_parameter_property ITER_WIDTH DEFAULT_VALUE 8
set_parameter_property ITER_WIDTH DISPLAY_NAME ITER_WIDTH
set_parameter_property ITER_WIDTH TYPE INTEGER
set_parameter_property ITER_WIDTH UNITS None
set_parameter_property ITER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ITER_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s1c
# 
add_interface s1c clock end
set_interface_property s1c clockRate 0
set_interface_property s1c ENABLED true
set_interface_property s1c EXPORT_OF ""
set_interface_property s1c PORT_NAME_MAP ""
set_interface_property s1c SVD_ADDRESS_GROUP ""

add_interface_port s1c csi_s1_clk clk Input 1


# 
# connection point s1r
# 
add_interface s1r reset end
set_interface_property s1r associatedClock ""
set_interface_property s1r synchronousEdges NONE
set_interface_property s1r ENABLED true
set_interface_property s1r EXPORT_OF ""
set_interface_property s1r PORT_NAME_MAP ""
set_interface_property s1r SVD_ADDRESS_GROUP ""

add_interface_port s1r rsi_s1_reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s1c
set_interface_property s1 associatedReset s1r
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_address address Input 3
add_interface_port s1 avs_s1_write write Input 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m1c
# 
add_interface m1c clock end
set_interface_property m1c clockRate 0
set_interface_property m1c ENABLED true
set_interface_property m1c EXPORT_OF ""
set_interface_property m1c PORT_NAME_MAP ""
set_interface_property m1c SVD_ADDRESS_GROUP ""

add_interface_port m1c csi_m1_clk clk Input 1


# 
# connection point m1r
# 
add_interface m1r reset end
set_interface_property m1r associatedClock ""
set_interface_property m1r synchronousEdges NONE
set_interface_property m1r ENABLED true
set_interface_property m1r EXPORT_OF ""
set_interface_property m1r PORT_NAME_MAP ""
set_interface_property m1r SVD_ADDRESS_GROUP ""

add_interface_port m1r rsi_m1_reset reset Input 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock m1c
set_interface_property m1 associatedReset m1r
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_writedata writedata Output 8
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1

