# TCL File Generated by Component Editor 13.0sp1
# Sat Oct 12 18:33:16 JST 2013
# DO NOT MODIFY


# 
# avs_wbm_bridge "Avalon-MM Slave to Wishbone Master Bridge" v1.0
# kimu_shu 2013.10.12.18:33:16
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avs_wbm_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME avs_wbm_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Bridges/Memory-Mapped
set_module_property AUTHOR kimu_shu
set_module_property DISPLAY_NAME "Avalon-MM Slave to Wishbone Master Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avs_wbm_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avs_wbm_bridge.vhd VHDL PATH avs_wbm_bridge.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 1
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 1
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter WORD_WIDTH INTEGER 8
set_parameter_property WORD_WIDTH DEFAULT_VALUE 8
set_parameter_property WORD_WIDTH DISPLAY_NAME WORD_WIDTH
set_parameter_property WORD_WIDTH TYPE INTEGER
set_parameter_property WORD_WIDTH UNITS None
set_parameter_property WORD_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WORD_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clock
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_address address Input addr_width
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input word_width
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_readdata readdata Output word_width
add_interface_port avs avs_waitrequest waitrequest Output 1
add_interface_port avs avs_chipselect chipselect Input 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point wbm
# 
add_interface wbm conduit end
set_interface_property wbm associatedClock clock
set_interface_property wbm associatedReset reset
set_interface_property wbm ENABLED true
set_interface_property wbm EXPORT_OF ""
set_interface_property wbm PORT_NAME_MAP ""
set_interface_property wbm SVD_ADDRESS_GROUP ""

add_interface_port wbm wbm_adr_o adr Output addr_width
add_interface_port wbm wbm_dat_i dat_r Input word_width
add_interface_port wbm wbm_dat_o dat_w Output word_width
add_interface_port wbm wbm_we_o we Output 1
add_interface_port wbm wbm_stb_o stb Output 1
add_interface_port wbm wbm_ack_i ack Input 1
add_interface_port wbm wbm_cyc_o cyc Output 1

